// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zola.Database;

#nullable disable

namespace Zola.Database.Migrations
{
    [DbContext(typeof(MsfDbContext))]
    [Migration("20230709164347_4697D9E3-5DE6-4F14-B408-40B60B34C551")]
    partial class _4697D9E35DE64F14B40840B60B34C551
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("CharacterInfoTrait", b =>
                {
                    b.Property<string>("CharactersId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharactersId", "TraitsId");

                    b.HasIndex("TraitsId");

                    b.ToTable("CharacterInfoTrait");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.Ability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level3Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level4Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level5Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level6Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level7Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Level1Id");

                    b.HasIndex("Level2Id");

                    b.HasIndex("Level3Id");

                    b.HasIndex("Level4Id");

                    b.HasIndex("Level5Id");

                    b.HasIndex("Level6Id");

                    b.HasIndex("Level7Id");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.AbilityKit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BasicId");

                    b.HasIndex("PassiveId");

                    b.HasIndex("SpecialId");

                    b.HasIndex("UltimateId");

                    b.ToTable("AbilityKit");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.AbilityLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CostEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextUpgrade")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartEnergy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AbilityLevel");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.CharacterInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilityKitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpoweredAbilityKitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier10Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier11Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier12Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier13Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier14Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier15Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier16Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier17Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier3Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier4Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier5Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier6Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier7Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier8Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTier9Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Portrait")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnlockStars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityKitId");

                    b.HasIndex("EmpoweredAbilityKitId");

                    b.HasIndex("GearTier10Id");

                    b.HasIndex("GearTier11Id");

                    b.HasIndex("GearTier12Id");

                    b.HasIndex("GearTier13Id");

                    b.HasIndex("GearTier14Id");

                    b.HasIndex("GearTier15Id");

                    b.HasIndex("GearTier16Id");

                    b.HasIndex("GearTier17Id");

                    b.HasIndex("GearTier1Id");

                    b.HasIndex("GearTier2Id");

                    b.HasIndex("GearTier3Id");

                    b.HasIndex("GearTier4Id");

                    b.HasIndex("GearTier5Id");

                    b.HasIndex("GearTier6Id");

                    b.HasIndex("GearTier7Id");

                    b.HasIndex("GearTier8Id");

                    b.HasIndex("GearTier9Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.GearSlot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearTierId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PieceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GearTierId");

                    b.HasIndex("PieceId");

                    b.ToTable("GearSlot");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.GearTier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterInfoId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatsId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterInfoId");

                    b.HasIndex("CharacterInfoId1");

                    b.HasIndex("StatsId");

                    b.ToTable("GearTier");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemMember1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializationHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("String")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemMember1Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.ItemMember1", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullArt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCalendar")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsOrb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("NoDeco")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NoInv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopArt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatsId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatsId");

                    b.ToTable("ItemMember1");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.Stats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockChance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CritChance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CritDamageBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DamageReduction")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DodgeChance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExtraHeal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Focus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Resist")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.Trait", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("CharacterInfoTrait", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.CharacterInfo", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zola.MsfClient.Models.Trait", null)
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zola.MsfClient.Models.Ability", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level1")
                        .WithMany()
                        .HasForeignKey("Level1Id");

                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level2")
                        .WithMany()
                        .HasForeignKey("Level2Id");

                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level3")
                        .WithMany()
                        .HasForeignKey("Level3Id");

                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level4")
                        .WithMany()
                        .HasForeignKey("Level4Id");

                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level5")
                        .WithMany()
                        .HasForeignKey("Level5Id");

                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level6")
                        .WithMany()
                        .HasForeignKey("Level6Id");

                    b.HasOne("Zola.MsfClient.Models.AbilityLevel", "Level7")
                        .WithMany()
                        .HasForeignKey("Level7Id");

                    b.Navigation("Level1");

                    b.Navigation("Level2");

                    b.Navigation("Level3");

                    b.Navigation("Level4");

                    b.Navigation("Level5");

                    b.Navigation("Level6");

                    b.Navigation("Level7");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.AbilityKit", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.Ability", "Basic")
                        .WithMany()
                        .HasForeignKey("BasicId");

                    b.HasOne("Zola.MsfClient.Models.Ability", "Passive")
                        .WithMany()
                        .HasForeignKey("PassiveId");

                    b.HasOne("Zola.MsfClient.Models.Ability", "Special")
                        .WithMany()
                        .HasForeignKey("SpecialId");

                    b.HasOne("Zola.MsfClient.Models.Ability", "Ultimate")
                        .WithMany()
                        .HasForeignKey("UltimateId");

                    b.Navigation("Basic");

                    b.Navigation("Passive");

                    b.Navigation("Special");

                    b.Navigation("Ultimate");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.CharacterInfo", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.AbilityKit", "AbilityKit")
                        .WithMany()
                        .HasForeignKey("AbilityKitId");

                    b.HasOne("Zola.MsfClient.Models.AbilityKit", "EmpoweredAbilityKit")
                        .WithMany()
                        .HasForeignKey("EmpoweredAbilityKitId");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier10")
                        .WithMany()
                        .HasForeignKey("GearTier10Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier11")
                        .WithMany()
                        .HasForeignKey("GearTier11Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier12")
                        .WithMany()
                        .HasForeignKey("GearTier12Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier13")
                        .WithMany()
                        .HasForeignKey("GearTier13Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier14")
                        .WithMany()
                        .HasForeignKey("GearTier14Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier15")
                        .WithMany()
                        .HasForeignKey("GearTier15Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier16")
                        .WithMany()
                        .HasForeignKey("GearTier16Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier17")
                        .WithMany()
                        .HasForeignKey("GearTier17Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier1")
                        .WithMany()
                        .HasForeignKey("GearTier1Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier2")
                        .WithMany()
                        .HasForeignKey("GearTier2Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier3")
                        .WithMany()
                        .HasForeignKey("GearTier3Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier4")
                        .WithMany()
                        .HasForeignKey("GearTier4Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier5")
                        .WithMany()
                        .HasForeignKey("GearTier5Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier6")
                        .WithMany()
                        .HasForeignKey("GearTier6Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier7")
                        .WithMany()
                        .HasForeignKey("GearTier7Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier8")
                        .WithMany()
                        .HasForeignKey("GearTier8Id");

                    b.HasOne("Zola.MsfClient.Models.GearTier", "GearTier9")
                        .WithMany()
                        .HasForeignKey("GearTier9Id");

                    b.Navigation("AbilityKit");

                    b.Navigation("EmpoweredAbilityKit");

                    b.Navigation("GearTier1");

                    b.Navigation("GearTier10");

                    b.Navigation("GearTier11");

                    b.Navigation("GearTier12");

                    b.Navigation("GearTier13");

                    b.Navigation("GearTier14");

                    b.Navigation("GearTier15");

                    b.Navigation("GearTier16");

                    b.Navigation("GearTier17");

                    b.Navigation("GearTier2");

                    b.Navigation("GearTier3");

                    b.Navigation("GearTier4");

                    b.Navigation("GearTier5");

                    b.Navigation("GearTier6");

                    b.Navigation("GearTier7");

                    b.Navigation("GearTier8");

                    b.Navigation("GearTier9");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.GearSlot", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.GearTier", null)
                        .WithMany("Slots")
                        .HasForeignKey("GearTierId");

                    b.HasOne("Zola.MsfClient.Models.Item", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceId");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.GearTier", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.CharacterInfo", null)
                        .WithMany("GearTiers")
                        .HasForeignKey("CharacterInfoId");

                    b.HasOne("Zola.MsfClient.Models.CharacterInfo", null)
                        .WithMany("gearTiers")
                        .HasForeignKey("CharacterInfoId1");

                    b.HasOne("Zola.MsfClient.Models.Stats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.Item", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.ItemMember1", "ItemMember1")
                        .WithMany()
                        .HasForeignKey("ItemMember1Id");

                    b.Navigation("ItemMember1");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.ItemMember1", b =>
                {
                    b.HasOne("Zola.MsfClient.Models.Stats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.CharacterInfo", b =>
                {
                    b.Navigation("GearTiers");

                    b.Navigation("gearTiers");
                });

            modelBuilder.Entity("Zola.MsfClient.Models.GearTier", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
