# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /Zola.MsfClient
COPY Zola.MsfClient/*.csproj .
RUN dotnet restore
COPY Zola.MsfClient .
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
ENTRYPOINT ["dotnet", "Zola.MsfClient.dll"]




#FROM mcr.microsoft.com/dotnet/aspnet:7.0
#RUN pwd
#RUN ls
#WORKDIR ../Zola.MsfClient/bin/Release/net7.0/publish
#COPY ../Zola.MsfClient/bin/Release/net7.0/publish .
#ENTRYPOINT ["dotnet", "Zola.MsfClient.dll"]
