# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /src
#COPY src/Zola.*/*.csproj .

COPY src/Zola.Console/Zola.Console.csproj ./Zola.Console/Zola.Console.csproj
COPY src/Zola.MsfClient/Zola.MsfClient.csproj ./Zola.MsfClient/Zola.MsfClient.csproj
COPY src/Zola.Database/Zola.Database.csproj ./Zola.Database/Zola.Database.csproj
COPY src/Zola.Discord/Zola.Discord.csproj ./Zola.Discord/Zola.Discord.csproj
COPY src/Zola.Web/Zola.Web.csproj ./Zola.Web/Zola.Web.csproj

COPY src/Zola.sln .
RUN dotnet restore

COPY src .
#RUN dotnet publish -c Release
RUN dotnet publish -c Release -o /publish
WORKDIR /publish
#COPY /publish .
