# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
FROM michaeldonnelly/zola-core as core
WORKDIR /publish
#COPY --from=core * .
ENTRYPOINT ["dotnet", "Zola.Discord.dll"]
