# syntax=docker/dockerfile:1

FROM michaeldonnelly/zola-core
#WORKDIR /publish
COPY --from=build-env /publish .
ENTRYPOINT ["dotnet", "Zola.MsfClient.dll"]




#FROM mcr.microsoft.com/dotnet/aspnet:7.0
#RUN pwd
#RUN ls
#WORKDIR ../Zola.MsfClient/bin/Release/net7.0/publish
#COPY ../Zola.MsfClient/bin/Release/net7.0/publish .
#ENTRYPOINT ["dotnet", "Zola.MsfClient.dll"]
