version: '3.2'
services:
  pressgang-bot:
    container_name: zola-test
    image: "michaeldonnelly/pressgang-bot:latest"
    environment:
      TZ: 'America/Chicago'
    volumes:
      - type: bind
        source: ./appsettings.Staging.json
        target: /App/appsettings.json
      - type: bind
        source: ../Data
        target: /Data
      - type: bind
        source: ../msf-press-gang/PressGang.Core/Import
        target: /App/Import
    restart: unless-stopped
    privileged: true
