name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - run: ls
    - run: ls Docker
    - name: Build the Docker image for zola-core
      run: docker build . --file Docker/Dockerfile-Core --tag michaeldonnelly/zola-core:$(date -u +"%Y-%m-%d-%H%M")
    - name: Build the Docker image for Discord
      run: docker build . --file Docker/Dockerfile-Discord --tag michaeldonnelly/zola-discord:$(date -u +"%Y-%m-%d-%H%M")
    - name: Build the Docker image for the web site
      run: docker build . --file Docker/Dockerfile-Web --tag michaeldonnelly/zola-web:$(date -u +"%Y-%m-%d-%H%M")
