name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "timestamp=$(date -u +"%Y-%m-%d-%H%M")" >> "$GITHUB_ENV"
    - run: echo $timestamp
    - run: ls
    - run: ls Docker
    - name: Build the Docker image for zola-core
      run: docker build . --file Docker/Dockerfile-Core --tag michaeldonnelly/zola-core
    - name: Tag zola-core with a timestamp
      run: docker tag michaeldonnelly/zola-core michaeldonnelly/zola-core:$timestamp
    - name: Build the Docker image for Discord
      run: docker build . --file Docker/Dockerfile-Discord --tag michaeldonnelly/zola-discord:$timestamp
    - name: Build the Docker image for the web site
      run: docker build . --file Docker/Dockerfile-Web --tag michaeldonnelly/zola-web:$timestamp
