name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for zola-core
      run: docker build . --file Docker/Dockerfile-Core --tag michaeldonnelly/zola-core
    - name: Build the Docker image for the Discord bot
      run: docker build . --file Docker/Dockerfile-Discord --tag michaeldonnelly/zola-discord
    - name: Build the Docker image for the web site
      run: docker build . --file Docker/Dockerfile-Web --tag michaeldonnelly/zola-web
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag and publish docker images
      run: Docker/publish.sh
